# Generated by Django 5.0.2 on 2024-02-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_productsubcat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcat',
            name='image',
            field=models.FileField(default='default.jpeg', upload_to='upload'),
        ),
    ]
